application: engineapp
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /images
  static_dir: static/images

- url: /hello\.html
  static_files: static/hello.html
  upload: static/hello.html

- url: .*
  script: thesite.main.app

libraries:
- name: webapp2
  version: "2.5.1"

